project:
  type: website
  output-dir: ../docs  # Goes to root-level docs/ folder

website:
  title: "DIVE Platform"
  navbar:
    left:
      - text: About
        file: about.qmd
      - text: Genome Browser
        href: jbrowse/index.html
    right:
      - icon: github
        href: https://github.com/urol-e5/deep-dive-genome-browser
        aria-label: GitHub

format:
  html:
    theme:
      light: litera
      dark: darkly

    toc: true